name: "🚀Publish YCSS"

on: 
  push:
    branches:
      - master

jobs:
  release:
    name: 🚀Publish YCSS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Node.js ${{ matrix.node }} environment
        uses: actions/setup-node@v3.4.0
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
      - name: 🚀Publish YCSS
        run: npm publish --access public
        working-directory: ycss
        env: 
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}




  
