name: "🚀Publish YCSS"

on: 
  push:
    branches:
      - master

jobs:
  release:
    name: 🚀Publish YCSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
            path: main
      - name: Setup Node.js 16 environment
        uses: actions/setup-node@v3.4.0
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: 🚀Publish YCSS
        run: npm publish --access public
        working-directory: yc-css
        env: 
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}




  
